# Generated by Django 2.2.10 on 2020-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60)),
                ('semester_name', models.CharField(max_length=60)),
                ('course_name', models.CharField(max_length=60)),
                ('course_code', models.CharField(max_length=60)),
                ('section', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=255)),
                ('project_file', models.FileField(upload_to='media/files/projects/%Y/%m/%d/')),
                ('document', models.FileField(upload_to='files/documents/%Y/%m/%d/')),
                ('thumbnail', models.FileField(upload_to='thumbnail/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis_title', models.CharField(max_length=60)),
                ('semester_name', models.CharField(max_length=60)),
                ('course_name', models.CharField(max_length=60)),
                ('course_code', models.CharField(max_length=60)),
                ('section', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=255)),
                ('thesis_file', models.FileField(upload_to='files/Thesis/%Y/%m/%d/')),
                ('thumbnail', models.FileField(upload_to='thumbnail/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
