# Generated by Django 2.2.10 on 2020-08-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='course_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='course_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='files/projects/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='project_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='section',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='semester_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail/%Y/%m/%d/'),
        ),
    ]
