# Generated by Django 2.2.13 on 2020-10-27 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ProjectDocument')),
                ('theses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ThesisPaper')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
