# Generated by Django 2.2.10 on 2020-09-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='user',
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='student_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='username',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
