# Generated by Django 2.2.10 on 2020-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesispaper',
            name='course_code',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='course_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='section',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='semester_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='thesis_file',
            field=models.FileField(null=True, upload_to='files/Thesis/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='thesis_title',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thesispaper',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnail/%Y/%m/%d/'),
        ),
    ]
