# Generated by Django 2.2.13 on 2020-10-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_projectthesis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectThesis',
        ),
    ]
