# Generated by Django 2.2.10 on 2020-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.FileField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
